server:
  port: 18086
  servlet:
    context-path: /nacos-provider

spring.application.name: service-provider

nacos.discovery.server-addr: 127.0.0.1:8848

#spring:
#  application:
#    name: nacos-provider
#
#nacos:
#  discovery:
#    server-addr: 127.0.0.1:8848