server:
  port: 18089
  servlet:
    context-path: /amqp
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /base

spring:
  application:
    # 应用名称/日志文件名称
    name: amqp
