server:
  port: 18082
  servlet:
    context-path: /jetcache

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson

  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      expireAfterWriteInMillis: 3600000
      host: 47.113.120.106
      port: 6379
